name: 'labelmaker'
description: 'Apply labels to issues and PRs automatically.'
author: 'tylerbutler'
inputs:
  config: # change this
    required: true
    description: 'path to config file'
    default: '.github/labelmaker.yml'

runs:
  using: 'node12'
  main: 'dist/index.js'
